version: '2.4'

services:
  logstash:
    container_name: logstash
    command: /usr/share/plugins/plugin/.ci/run.sh
    environment:
      - ELASTIC_STACK_VERSION=$ELASTIC_STACK_VERSION
    depends_on:
      - redis
      - redis_ssl
    networks:
      app_net:
        ipv4_address: 172.16.238.10
        ipv6_address: 2001:3984:3989::10
  redis:
    image: redis
    hostname: redis
    container_name: redis
    command: --port 16379
    ports:
      - "16379:16379/tcp"
    networks:
      app_net:
        ipv4_address: 172.16.238.161
        ipv6_address: 2001:3984:3989::161
  redis_ssl:
    hostname: redis_ssl
    container_name: redis_ssl
    ports:
      - "26379:26379/tcp"
    networks:
      app_net:
        ipv4_address: 172.16.238.162
        ipv6_address: 2001:3984:3989::162
    build:
      context: ../
      dockerfile: .ci/Dockerfile.redis_ssl
    environment:
      - PORT=26379
networks:
  app_net:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
        - subnet: 2001:3984:3989::/64
          gateway: 2001:3984:3989::1